runtime: php
env: flex

runtime_config:
  document_root: public

# Ensure we skip ".env", which is only for local development
skip_files:
  - .env

env_variables:
  # Put production environment variables here.
  APP_LOG: errorlog
  APP_KEY: base64:UVkA53ZTQrITyKCccI24/v9+J5P3P/X5nmL89se6YnI=
  STORAGE_DIR: /tmp

  